apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: a7db653049aaa4a578d594097e98b0fa-1122827328.ap-southeast-2.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portainer-demo-service
            port:
              number: 80
